### ISSUE TITLE
Adding a SOCKS5 communication layer

### ISSUE THREAD

**Issue by lbarman** [lbarman/prifi#12]
Branch: PriFi-SDA

**Comment by elhajjj** [comment]
I'm still working on the PriFi-independent client-server (i.e relay) implementation. I have the initial communication setup that SOCKS5 requires (function selection and connecting to web server) completely functional, yet after a success message is sent back to the browser the connection closes and I receive no HTTP GET message from the browser. 

This week I will try my best to get that to work.

**Comment by elhajjj** [comment]
I'm happy to say that the prifi-independent SOCKS5 is working well. It crashes on some websites I'm not sure why but I will look into it.

The code needs refactoring and commenting.

If you'd like to test it out it's in the "SOCK5" directory in the prifi_dev repo, just run the two go files (server first, then client) and connect the browser to SOCKS5 on port 6789!

**Comment by lbarman** [comment]
I just checked out "SOCK5-simul", but I cannot find something like server.go/client.go. Did you push, or what did I missed ?
Thanks

**Comment by elhajjj** [comment]
Sorry, I ended up coding everything under the branch "PriFi-moehajj". I also made a lot of code refactoring end of last week and beginning of this week to make it easier and more user-friendly to use my code with PriFi. Yet things got a bit complicated, and it still gets a big stuck on a few pages, but you can still browse most websites!

If you'd like to test it out it's in the "SOCK5" directory in the prifi_dev repo under the PriFi-moehajj branch, just run the two go files (run-server.go first, then run-client.go) and connect the browser to SOCKS5 on port 6789!

If you wanna check out the code for the implementation, it's in the "prifi-socks" directory in the prifi_dev repo under the PriFi-moehajj branch.

**Comment by elhajjj** [comment]
Good news is the SOCKS5 integration with PriFi seems to be working but with some errors. Browsing is possible for a short period of time where then it crashes. I haven't yet pushed this version of the code onto Github since it doesn't really work 100% yet.

**Comment by elhajjj** [comment]
Updates (also found in the Wiki): 

Browsing with PriFi is smooth, however with big sophisticated websites browsing gets stuck (I think it's a packet loss/modification issue)
Moved SOCKS5 connection setup phase complete to the client side to preserve the clients IP anonymity

EDIT: (A more detailed explanation for the moving of the SOCKS5 setup phase)

So till now we have SOCKS handlers operating above the PriFi client and relay, and they connect with a SOCKS server which is independent of PriFi. The implementation allows tunneling of packets from the browser, through PriFi, and finally to the SOCKS server which handles the packets.

Every time the browser establishes a new SOCKS connection (which is frequent), there is a setup phase that occurs before any web data is transmitted. This setup phase was initially handled by the SOCKS server, meaning the packets had to get tunneled through PriFi to the SOCKS server and then back to the browser. 

However, this setup includes information about the clients IP address and port number he's using, which causes an issue in preserving the clients anonymity since these packets are tunneled through the relay.

As a result, I moved all SOCKS setup communications that happen with the browser to the client side, this way we preserve the anonymity of the client in the network.
